### ISSUE TITLE
for reduce method

### ISSUE THREAD

**Issue by MachineGUN001** [BIMSBbioinfo/Compass#1]
hi,

Thank you for providing this interesting work! I have a question regarding the usage of the "reduce" [method.](https://github.com/rlabduke/reduce). It seems that the developer only supports the Unix version, and I am using the Windows operating system which may not be compatible. 

while I try to run the compass script without reduce method, the following warning info:

```python
    print("***** WARNING: reduce is not installed      *****")
    print("***** WARNING: clashes and interaction fingerprinting may not work *****")
    print("***** WARNING: we highly recommend using reduce as in the paper for comparison *****")
    print("***** WARNING: Install instructions in README.md *****")
```

If I run the Compass method without using "reduce" method will it still function correctly? Will it affect the accuracy and precision of the predicted results of docking?

many thanks,

Best,

**Comment by asarigun** [comment]
Hi @MachineGUN001,

Thank you for your interest and for bringing up this issue! We haven't tested our tool on Windows. However, I recommend setting up a virtual machine to run a Linux distribution, such as VirtualBox or VMware. Alternatively, you could try using the Windows Subsystem for Linux.

If 'reduce' is not installed correctly, you can still proceed with the docking simulations, but please be aware that you might not get information on the molecule conformations' strain energy, the number of clashes, and the interaction fingerprint of the complex. (You will still be able to obtain results for binding affinity).

Best,

**Comment by MachineGUN001** [comment]
got it. many thanks!

Best,
