### ISSUE TITLE
AttributeError: type object 'Molecule' has no attribute 'from_file'

### ISSUE THREAD

**Issue by MachineGUN001** [BIMSBbioinfo/Compass#2]
hi, 

please see the below error.

```bash
Traceback (most recent call last):
  File "c:\Users\lsy\anaconda3\envs\diffdock112\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\lsy\anaconda3\envs\diffdock112\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\Cheminfo_Workshop\5_Docking_Lab\Compass-main\main_inference.py", line 327, in <module>
    main()
  File "d:\Cheminfo_Workshop\5_Docking_Lab\Compass-main\main_inference.py", line 324, in main
    recursive_docking_and_processing(args)
  File "d:\Cheminfo_Workshop\5_Docking_Lab\Compass-main\main_inference.py", line 87, in recursive_docking_and_processing
    binding_aff, clashes, strain, confidence_value = process_sdf_file(write_dir, sdf_file, args, protein_path_list, iteration, ligand_description)
  File "d:\Cheminfo_Workshop\5_Docking_Lab\Compass-main\main_inference.py", line 168, in process_sdf_file
    clashes, strain, inter_dict = posecheck_eval(protein_path, input_sdf_path)
  File "d:\Cheminfo_Workshop\5_Docking_Lab\Compass-main\compass.py", line 83, in posecheck_eval
    pc.load_protein_from_pdb(protein_file)
  File "d:\cheminfo_workshop\5_docking_lab\compass-main\posecheck\posecheck\posecheck.py", line 59, in load_protein_from_pdb
    self.protein = load_protein_from_pdb(pdb_path, reduce_path=self.reduce_path)
  File "d:\cheminfo_workshop\5_docking_lab\compass-main\posecheck\posecheck\utils\loading.py", line 85, in load_protein_from_pdb
    prot = plf.Molecule.from_file(tmp_path)
AttributeError: type object 'Molecule' has no attribute 'from_file'

```

I used the ProLIF version 2.0.3 as environment.yml depicted. however,  the current version of ProLIF has remove the 'from_file" function from the Molecule class. May I know which right version of ProLIF you are using that still can allow for the proper usage of 'from_file" function?

many thanks,

Best,

**Comment by asarigun** [comment]
Hi,

I've confirmed that the version of ProLIF in my Conda environment is still 2.0.3.

You might want to try uninstalling and then reinstalling ProLIF to ensure there are no issues with the installation:

```bash
pip install prolif==2.0.3
```

Additionally, it's important to make sure that PoseCheck is also properly installed in your environment. Please follow these steps to install it:

```bash
cd posecheck/
pip install -e .
```

Let me know if you encounter any further issues. I'm here to help!

Best,

**Comment by MachineGUN001** [comment]
hi,

thanks for your kind explanation and confirm.

as you mentioned, I re-installed the ProLIF with version 2.0.3 via pip command.
then checked that Posecheck is installed properly as well.

I reviewed the code from Posecheck github repo as below link.
https://github.com/cch1999/posecheck/blob/main/posecheck/utils/loading.py
however, 
the function 'prot = plf.Molecule.from_file(tmp_path)' can be found in this script.

I am not sure where the `plf.Molecule.from_file` function is defined. 
the original code for Molecule class without  from_file function, which might cause the error

```bash
prot = plf.Molecule.from_file(tmp_path)
AttributeError: type object 'Molecule' has no attribute 'from_file'

```

many thanks,

Best,

**Comment by asarigun** [comment]
Hi,

Thank you for your feedback. I've reviewed the code and noticed that we use `plf.Molecule.from_file` at this location:

https://github.com/BIMSBbioinfo/Compass/blob/main/posecheck/posecheck/utils/loading.py#L85

I'm not sure why you're encountering this issue, but if you could share the command you used, I might be able to help better. Having the exact command would enable me to understand the problem more clearly.

Best,

**Comment by MachineGUN001** [comment]
hi,

I found this function in `loading.py` script as you mentioned.

```
    # Load the protein from the temporary PDB file
    prot = plf.Molecule.from_file(tmp_path)
    os.remove(tmp_path)
```
 
[molecule.zip](https://github.com/user-attachments/files/15882660/molecule.zip)
the uploaded file is about the `molecule` class in ProLif. 
there is no `from_file` function, which caused my errors. I think that's ProLif's issue not yours.

thanks for your kind help!

Best,
